is2_sgpa/sgpa/apps/proyectos/urls.py
from django.urls import path
from proyectos.views import (
    CrearRol,
    ListarRol,
    ListarUserStory,
    ListarUserStoryFinalizados,
    asignarRol,
    asignarSprint,
    asignarTareasSprint,
    avanzarEstadoTarea,
    cancelarSprint,
    crearTipoUS,
    crearUserStory,
    verUserStory,
    desasignarRol,
    desasignarSprint,
    editarRol,
    eliminarRol,
    eliminarUserStory,
    finalizarProyecto,
    finalizarSprint,
    home,
    iniciarSprint,
    miembroCrear,
    miembroEliminar,
    modificarUserStory,
    modificarUserStoryKanban,
    retrocederEstadoTarea,
    tableroKanban,
    verMiembros,
    verProyecto,
    crearProyecto,
    ListarTipoUserStory,
    iniciarProyecto,
    cancelarProyecto,
    listarProyectos,
    eliminarProyecto,
    modificarProyecto,
    proy,
    crearSprint,
    listarSprints,
    verHistorial,
    modificarSprints,
    eliminarSprint,
    eliminarTipo,
    verRoles,
    modificarTipoUS,
    cancelarUs,
    miembroSprintCrear,
    verMiembrosSprint,
    miembroSprintEliminar,
    burndownchart,
)

urlpatterns = [
    path("", proy, name="proy"),
    path("home/", home, name="home"),
    path("nuevo/", crearProyecto.as_view(), name="nuevo_proyecto"),
    path("listar/", listarProyectos.as_view(), name="listar_proyectos"),
    path("eliminar/<int:id_proyecto>/", eliminarProyecto, name="eliminar_proyectos"),
    path("<int:id_proyecto>/", verProyecto, name="ver_proyecto"),
    path("modificar/<int:id_proyecto>/", modificarProyecto, name="modificar_proyecto"),
    path("<int:id_proyecto>/iniciar/", iniciarProyecto, name="iniciar_proyecto"),
    path("<int:id_proyecto>/finalizar/", finalizarProyecto, name="finalizar_proyecto"),
    path("<int:id_proyecto>/cancelar/", cancelarProyecto, name="cancelar_proyecto"),
    path("<int:id_proyecto>/sprint", crearSprint, name="nuevo_sprint"),
    path(
        "<int:id_proyecto>/sprint/modificar/<int:id_sprint>",
        modificarSprints,
        name="modificar_sprint",
    ),
    path("<int:id_proyecto>/sprint/listar", listarSprints, name="listar_sprints"),
    path(
        "<int:id_proyecto>/sprint/eliminar/<int:id_sprint>/",
        eliminarSprint,
        name="eliminar_sprint",
    ),
    path(
        "<int:id_proyecto>/sprint/iniciar/<int:id_sprint>/",
        iniciarSprint,
        name="iniciar_sprint",
    ),
    path(
        "<int:id_proyecto>/sprint/cancelar/<int:id_sprint>/",
        cancelarSprint,
        name="cancelar_sprint",
    ),
    path(
        "<int:id_proyecto>/sprint/finalizar/<int:id_sprint>/",
        finalizarSprint,
        name="finalizar_sprint",
    ),
    path(
        "<int:idProyecto>/sprint/kanban/<int:idSprint>/",
        tableroKanban,
        name="kanban",
    ),
    path(
        "<int:idProyecto>/sprint/tareas/<int:idSprint>/",
        asignarTareasSprint,
        name="sprint_tareas",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/tarea/<int:idTarea>/asignar_sprint",
        asignarSprint,
        name="asignar_sprint",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/tarea/<int:idTarea>/desasignar_sprint",
        desasignarSprint,
        name="desasignar_sprint",
    ),
    path(
        "<int:idProyecto>/sprint/kanban/<int:idSprint>/tarea-avanzar/<int:idTarea>/",
        avanzarEstadoTarea,
        name="avanzar_tarea",
    ),
    path(
        "<int:idProyecto>/sprint/kanban/<int:idSprint>/tarea-retroceder/<int:idTarea>/",
        retrocederEstadoTarea,
        name="retroceder_tarea",
    ),
    path(
        "<int:idProyecto>/sprint/kanban/tareas/editar/<int:id_tarea>/",
        modificarUserStoryKanban,
        name="modificar_tarea_kanban",
    ),
    # Historial
    path("<int:id_proyecto>/historial/", verHistorial, name="ver_historial"),
    # Miembros
    path("<int:idProyecto>/miembros/listar/", verMiembros, name="listar_miembros"),
    path("<int:idProyecto>/miembros/nuevo/", miembroCrear, name="nuevo_miembro"),
    # Miembros Sprint
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/miembros/listar/",
        verMiembrosSprint,
        name="listar_miembros_sprint",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/miembros/nuevo/",
        miembroSprintCrear,
        name="nuevo_miembro_sprint",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/miembros/eliminar/<int:idMiembro>/",
        miembroSprintEliminar,
        name="eliminar_miembro_sprint",
    ),
    path(
        "<int:idProyecto>/miembros/eliminar/<int:idMiembro>/",
        miembroEliminar,
        name="eliminar_miembro",
    ),
    path(
        "<int:idProyecto>/miembros/<int:idMiembro>/roles/", verRoles, name="ver_roles"
    ),
    path(
        "<int:idProyecto>/miembros/<int:idMiembro>/roles/<int:idRol>/asignar/",
        asignarRol,
        name="asignar_rol",
    ),
    path(
        "<int:idProyecto>/miembros/<int:idMiembro>/roles/<int:idRol>/desasignar/",
        desasignarRol,
        name="desasignar_rol",
    ),
    # Roles
    path("<int:idProyecto>/roles/nuevo/", CrearRol.as_view(), name="crear_rol"),
    path("<int:idProyecto>/roles/listar/", ListarRol.as_view(), name="listar_roles"),
    path(
        "<int:idProyecto>/roles/eliminar/<int:id_rol>/",
        eliminarRol,
        name="eliminar_rol",
    ),
    path("<int:idProyecto>/roles/editar/<int:id_rol>/", editarRol, name="editar_rol"),
    # User Stories
    path("<int:idProyecto>/tareas/nuevo/", crearUserStory, name="crear_tarea"),
    path(
        "<int:idProyecto>/tareas/listar/",
        ListarUserStory.as_view(),
        name="listar_tareas",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/tareas/listar/finalizados/",
        ListarUserStoryFinalizados.as_view(),
        name="listar_tareas_finalizadas",
    ),
    path(
        "<int:idProyecto>/tipos/listar/",
        ListarTipoUserStory.as_view(),
        name="listar_tipos",
    ),
    path(
        "<int:idProyecto>/tipos/eliminar/<int:id_tipo>/",
        eliminarTipo,
        name="eliminar_tipo",
    ),
    path(
        "<int:idProyecto>/tipos/modificar/<int:id_tipo>/",
        modificarTipoUS,
        name="modificar_tipo",
    ),
    path(
        "<int:idProyecto>/tareas/eliminar/<int:id_tarea>/",
        eliminarUserStory,
        name="eliminar_tarea",
    ),
    path(
        "<int:idProyecto>/tareas/editar/<int:id_tarea>/",
        modificarUserStory,
        name="modificar_tarea",
    ),
    path(
        "<int:idProyecto>/tareas/ver/<int:id_tarea>/",
        verUserStory,
        name="ver_tarea",
    ),
    path(
        "<int:idProyecto>/tareas/tipo/",
        crearTipoUS,
        name="tipos_us",
    ),
    path(
        "<int:idProyecto>/tareas/cancelar/",
        cancelarUs,
        name="cancelar_tareas",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/burndownchart/",
        burndownchart,
        name="burndownchart",
    ),
]

is2_sgpa/sgpa/apps/usuarios/urls.py
from django.urls import path
from .views import (
    CrearPerfil,
    ListarPerfil,
    administrador,
    concederAcceso,
    editarPerfil_Admin,
    editarPerfil_General,
    eliminarPerfil,
    home,
    listaAcceso,
    proyectosUsuario,
)


urlpatterns = [
    path("", home, name="home"),
    path("nuevo/", CrearPerfil.as_view(), name="solicitar_acceso"),
    path("listar/", ListarPerfil.as_view(), name="listar_perfiles"),
    path("<int:id_usuario>/", proyectosUsuario, name="proyectos_usuario"),
    path("perfil/<int:id_perfil>/", editarPerfil_General, name="editar_perfilGeneral"),
    path("administrador/", administrador, name="administrador"),
    path("acceso/", listaAcceso, name="lista_acceso"),
    path("editar/<int:id_perfil>/", editarPerfil_Admin, name="editar_perfil"),
    path("eliminar/<int:id_perfil>/", eliminarPerfil, name="eliminar_perfil"),
    path("administrador/<int:id_perfil>", concederAcceso, name="conceder_acceso"),
]

is2_sgpa/sgpa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path(
        "login",
        auth_views.LoginView.as_view(template_name="cuenta/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("", include("usuarios.urls")),
    path("usuarios/", include(("usuarios.urls", "usuarios"), namespace="usuarios")),
    path("proyectos/", include(("proyectos.urls", "proyectos"), namespace="proyectos")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

is2_sgpa/sgpa/apps/usuarios/views.py
from django.db.models import Q
from usuarios.models import Perfil
from django.contrib import messages
from django.urls import reverse_lazy
from proyectos.models import Miembro, Proyecto
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import CreateView
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from usuarios.forms import Perfil_Form, Usuario_Form, PerfilEdit_Form
from django.contrib.auth.models import User, Permission
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

#def home
def home(request):
    """
        :param root_path: root path to search isHiddenWithinTree, defaults to "../data_in/"
        :type root_path: str, optional
    """
    if request.user.is_authenticated:
        return render(request, "home.html")
    else:
        return redirect("login")


# --- Creación de Perfil --- #
#crear perfil
class CrearPerfil(LoginRequiredMixin, CreateView):
    """
    Clase para la creacion de un perfil de usuario
    Hereda de la clase genérica CreateView
    Requiere inicio de sesión
    """

    model = Perfil
    form_class = Perfil_Form
    template_name = "usuarios/nuevo_perfil.html"
    success_url = reverse_lazy("proyectos:home")

    def form_valid(self, form):
        user = User.objects.get(username=self.request.user)
        Perfil.objects.create(
            user=user,
            ci=self.request.POST["ci"],
            telefono=self.request.POST["telefono"],
        )
        return redirect(self.success_url)


# --- Edición de Perfil --- #
#editar perfil general
@login_required
def editarPerfil_General(request, id_perfil):
    """
    Vista para la edición de los datos de un usuario (el email y el ci no puede ser modificado)
    Recibe el request HTTP y el id del perfil de un usuario
    Devuelve la renderización de la información del usuario
    Requiere inicio de sesión
    """
    perfil = Perfil.objects.get(id=id_perfil)
    usuario = User.objects.get(id=perfil.user.id)
    if request.method == "GET":
        perfil_Form = PerfilEdit_Form(instance=perfil)
        usuario_Form = Usuario_Form(instance=usuario)
    else:
        perfil_Form = PerfilEdit_Form(request.POST, instance=perfil)
        usuario_Form = Usuario_Form(request.POST, instance=usuario)
        if all([perfil_Form.is_valid(), usuario_Form.is_valid()]):
            perfil_Form.save(usuario=usuario, telefono=perfil.telefono)
            usuario_Form.save()
        return redirect("usuarios:proyectos_usuario", id_perfil)
    return render(
        request,
        "usuarios/editar_perfilGeneral.html",
        {"perfil_Form": perfil_Form, "usuario_Form": usuario_Form},
    )


# --- Proyectos de Usuario --- #
#proyecto de usuarios
@login_required
def proyectosUsuario(request, id_usuario):
    """
    Función que permite visualizar los proyectos de un determinado usuario
    Recibe el request HTTP y el id del usuario
    Retorna la renderización de los proyectos asociados en el template detallado
    Requiere inicio de sesión
    """

    usuario = User.objects.get(id=id_usuario)
    perfil = Perfil.objects.get(user=usuario)
    miembro = Miembro.objects.filter(idPerfil=perfil.id)
    return render(request, "usuarios/proyectos.html", {"miembros": miembro})


# ******************************** #
# *    Apartado Administrador    * #
# ******************************** #


@login_required
@permission_required("usuarios.autorizar_usuario", login_url="usuarios:home")
def administrador(request):
    """
    Obtiene la información acerca de todos los proyectos existentes, las solicitudes de acceso al sistema y el control de usuarios
    Recibe el request HTTP
    Retorna la renderización de la información ya mencionada en el template especificado
    Requiere inicio de sesión y permisos administrador
    """

    proyectos = Proyecto.objects.all()
    permiso = Permission.objects.get(codename="acceso_usuario")
    usuario = User.objects.filter(~Q(user_permissions=permiso), ~Q(id=1))
    perfilesAcceso = Perfil.objects.none()
    if len(usuario) > 0:
        perfilesAcceso = Perfil.objects.filter(Q(user=usuario[0]))
        for x in range(1, len(usuario)):
            perfilesAcceso |= Perfil.objects.filter(Q(user=usuario[x]))
    return render(
        request,
        "usuarios/administrador.html",
        {"perfilesAcceso": perfilesAcceso, "proyectos": proyectos},
    )


# --- Listar Solicitudes de Acceso --- #
#lista de accesos
@login_required
@permission_required("usuarios.autorizar_usuario", login_url="usuarios:home")
def listaAcceso(request):
    """
    Lista de las solicitudes de acceso al sistema
    Retorna la rendererización de la información solicitada en el template
    Recibe el request HTTP
    Requiere inicio de sesión y permisos administrador
    """

    perm = Permission.objects.get(codename="acceso_usuario")
    usuario = User.objects.filter(~Q(user_permissions=perm))
    perfiles = Perfil.objects.filter(Q(user=usuario[0]))
    for x in range(1, len(usuario)):
        perfiles |= Perfil.objects.filter(Q(user=usuario[x]))
    contexto = {"perfiles": perfiles}
    return render(request, "usuarios/usuario_acceso.html", contexto)


# --- Conceder Acceso al Sistema --- #
#conceder Acceso
@login_required
@permission_required("usuarios.autorizar_usuario", login_url="usuarios:home")
def concederAcceso(request, id_perfil):
    """
    Concede permiso de acceso al sistema y envía un email notificando lo acontecido al usuario
    Recibe el request HTTP y el id del perfil de usuario
    El retorno es una redirección a la página de solicitud
    Requiere inicio de sesión y permisos administrador
    """

    perfil = Perfil.objects.get(id=id_perfil)
    usuario = User.objects.get(id=perfil.user.id)
    perm = Permission.objects.get(codename="acceso_usuario")
    usuario.user_permissions.add(perm)
    send_mail(
        "Solicitud de acceso a SGPA",
        "¡Bienvenido a SGPA! Su solicitud de acceso al sistema fue aceptada",
        settings.EMAIL_HOST_USER,
        [usuario.email],
    )
    return redirect("usuarios:administrador")


# --- Listar Perfiles --- #
#listar perfiles
class ListarPerfil(LoginRequiredMixin, ListView):
    """
    Clase utilizada para listar los perfiles de usuarios existentes
    Hereda de la clase ListView
    Requiere inicio de sesión y permiso de administrador
    """

    redirect_field_name = "redirect_to"
    model = Perfil
    template_name = "usuarios/listar_perfiles.html"


# --- Editar Perfil --- #
#editar perfil admin
@login_required
def editarPerfil_Admin(request, id_perfil):
    """
    Vista para la edición de los datos de un usuario (el email puede ser modificado)
    Recibe el request HTTP y el id del perfil de un usuario
    Devuelve la renderización de la información del usuario
    Requiere inicio de sesión y permiso de administrador
    """

    perfil = Perfil.objects.get(id=id_perfil)
    usuario = User.objects.get(id=perfil.user.id)
    if request.method == "GET":
        perfil_Form = Perfil_Form(instance=perfil)
        usuario_Form = Usuario_Form(instance=usuario)
    else:
        perfil_Form = Perfil_Form(request.POST, instance=perfil)
        usuario_Form = Usuario_Form(request.POST, instance=usuario)
        if all([perfil_Form.is_valid(), usuario_Form.is_valid()]):
            perfil_Form.save(ci=perfil.ci, usuario=usuario, telefono=perfil.telefono)
            usuario_Form.save()
        return redirect("usuarios:listar_perfiles")
    return render(
        request,
        "usuarios/editar_perfil.html",
        {"perfil_Form": perfil_Form, "usuario_Form": usuario_Form},
    )


# --- Eliminar Perfil --- #
#eliminar perfil
@login_required
def eliminarPerfil(request, id_perfil):
    """
    Elimina el perfil del usuario solicitado
    Recibe el request HTTP y el id del perfil de usuario
    Retorna la renderización en el template especificado, en el cual solicita confirmación y luego redirige a la lista de perfiles
    Requiere inicio de sesión y permiso de administrador
    """

    perfil = Perfil.objects.get(id=id_perfil)
    miembro = Miembro.objects.filter(idPerfil=perfil.id)
    if not miembro:
        if request.method == "POST":
            usuario = User.objects.get(id=perfil.user.id)
            usuario.delete()
            perfil.delete()
            return redirect("usuarios:listar_perfiles")
        return render(request, "usuarios/eliminar_perfil.html", {"perfil": perfil})
    else:
        messages.add_message(
            request,
            messages.ERROR,
            "No se puede eliminar al usuario: %s  porque forma parte de un proyecto"
            % perfil.user.first_name,
        )
        return redirect("usuarios:listar_perfiles")

is2_sgpa/sgpa/templates/tareas/cancelar_tareas.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-4">
            <form method="POST">
                {% csrf_token %}
                <h3>Estás a punto de cancelar todas las Historias de Usuario</h3>
                <button type="submit" class="btn btn-danger">Confirmar</button>
                <a class="btn btn-primary" href="{% url 'proyectos:listar_tareas' idProyecto %}">Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

is2_sgpa/sgpa/templates/tareas/listar_tipos.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <ins>
        <h3 align="center">Lista de Tipos de User Stories</h3>
    </ins>
    {% if object_list %}
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">
            <table class="table">
                <thead align="center">
                    <tr class="table-primary">
                        <th scope="col">Nombre</th>
                        <th scope="col">Proyecto</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for us in object_list %}
                    <tr>
                        <td scope="col">{{ us.nombre }}</td>
                        <td scope="col">{{ us.proyecto }}</td>
                        <td scope="col">
                            {% if user.id == proyecto.scrumMaster.user.id%}
                            <a href="{% url 'proyectos:modificar_tipo' idProyecto us.id %}"
                                class="btn boton-color">Modificar
                            </a>
                            <a href="{% url 'proyectos:eliminar_tipo' idProyecto us.id %}"
                                class="btn boton-color">Eliminar
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <h4 align="center">El proyecto no tiene US creados</h4><br>
    {% endif %}
    <p align="center">
        {% if user.id == proyecto.scrumMaster.user.id%}
        <a href="{% url 'proyectos:tipos_us' idProyecto %}" class="btn boton-color">Crear Tipo</a>
        {% endif %}
        <a href="{% url 'proyectos:ver_proyecto' idProyecto %}" class="btn boton-color" role="button">Volver</a>
    </p>
</div>
{% endblock %}

is2_sgpa/sgpa/templates/tareas/listar_userStory.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <ins>
        <h3 align="center">Lista de User Stories - {{proyecto.nombre}}</h3>
    </ins>
    {% if object_list %}
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">
            <table class="table">
                <thead align="center">
                    <tr class="table-primary">
                        <th scope="col">Nombre</th>
                        <th scope="col">Tareas</th>
                        <th scope="col">Prioridad</th>
                        <th scope="col">Horas estimadas</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Desarrollador</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for us in object_list %}
                    <tr>
                        <td scope="col">{{ us.nombre }}</td>
                        <td scope="col">{{ us.descripcion }}</td>
                        <td scope="col">{{ us.prioridad_total }}</td>
                        <td scope="col">{{ us.horas_estimadas }}</td>
                        <td scope="col">{{ us.estado }}</td>
                        <td scope="col">
                            {% if us.desarrollador %}
                            {{ us.desarrollador }}
                            {% else %}
                            <p>No asignado</p>
                            {% endif %}
                        </td>
                        <td scope="col">
                            {% if user.id == proyecto.scrumMaster.user.id%}
                            <a href="{% url 'proyectos:modificar_tarea' idProyecto us.id %}"
                                class="btn boton-color">Modificar
                                US</a>
                            <a href="{% url 'proyectos:eliminar_tarea' idProyecto us.id %}"
                                class="btn boton-color">Eliminar
                                US</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <h4 align="center">El proyecto no tiene US creados</h4><br>
    {% endif %}
    <p align="center">
        {% if user.id == proyecto.scrumMaster.user.id%}
        <a href="{% url 'proyectos:crear_tarea' idProyecto %}" class="btn boton-color">Crear US</a>
        <a href="{% url 'proyectos:cancelar_tareas' idProyecto %}" class="btn btn-danger">Cancelar todas las US</a>
        {% endif %}
        <a href="{% url 'proyectos:ver_proyecto' idProyecto %}" class="btn boton-color" role="button">Volver</a>
    </p>
</div>
{% endblock %}

is2_sgpa/sgpa/templates/tareas/nuevo_userStory.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container-fluid">
    <ins>
        <h3 align="center">Crear nuevo US</h3>
    </ins>
    <br>
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-form-label">Tipo:</label>
                    {{ form.tipo }}
                </div>
                <td>
                    <a href="{% url 'proyectos:listar_tipos' idProyecto %}" class="btn buton-add" role="button">
                        </i>Añadir Tipo
                    </a>
                </td>
                <!-- <div class="form-group">
                    <label class="col-form-label">Sprint:</label>
                    {{ form.sprint }}
                </div> -->
                <!-- <div class="form-group">
                    <label class="col-form-label">Backlog:</label>
                    {{ form.backlog }}
                </div> -->

                <div class="form-group">
                    <label class="col-form-label">Nombre:</label>
                    {{ form.nombre }}
                </div>
                <div class="form-group">
                    <label class="col-form-label">Tareas:</label>
                    {{ form.descripcion }}
                </div>
                <div class="form-group">
                    <label class="col-form-label">Desarrollador:</label>
                    {{ form.desarrollador }}
                </div>
                <div class="form-group">
                    <label class="col-form-label">Horas estimadas:</label>
                    {{ form.horas_estimadas }}
                </div>

                <div class="form-group">
                    <label class="col-form-label">Prioridad funcional:</label>
                    {{ form.prioridad_funcional }}
                </div>
                <div class="form-group">
                    <label class="col-form-label">Prioridad tecnica:</label>
                    {{ form.prioridad_tecnica }}
                </div>


                <br>
                <p align="center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{% url 'proyectos:listar_tareas' idProyecto %}" class="btn btn-primary"
                        role="button">Cancelar</a>
                </p>
            </form>
        </div>
        <div class="col-md-3">
        </div>
    </div>
</div>

{% endblock %}

is2_sgpa/sgpa/templates/tareas/tareas_finalizadas.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <ins>
        <h3 align="center">Lista de User Stories - {{proyecto.nombre}}</h3>
    </ins>
    {% if object_list %}
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">
            <table class="table">
                <thead align="center">
                    <tr class="table-primary">
                        <th scope="col">Nombre</th>
                        <th scope="col">Tareas</th>
                        <th scope="col">Prioridad</th>
                        <th scope="col">Horas estimadas</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Desarrollador</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for us in object_list %}
                    <tr>
                        <td scope="col">{{ us.nombre }}</td>
                        <td scope="col">{{ us.descripcion }}</td>
                        <td scope="col">{{ us.prioridad_total }}</td>
                        <td scope="col">{{ us.horas_estimadas }}</td>
                        <td style="color: #198754;" scope="col">{{ us.estado }}</td>
                        <td scope="col">
                            {% if us.desarrollador %}
                            {{ us.desarrollador }}
                            {% else %}
                            <p>No asignado</p>
                            {% endif %}
                        </td>
                        <td scope="col">
                            <a href="{% url 'proyectos:ver_tarea' idProyecto us.id %}" class="btn boton-color">Ver
                                US</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <h4 align="center">El proyecto no tiene US finalizados</h4><br>
    {% endif %}
    <p align="center">
        <a href="{% url 'proyectos:kanban' idProyecto idSprint %}" class="btn boton-color" role="button">Volver</a>
    </p>
</div>
{% endblock %}