is2_sgpa/sgpa/apps/proyectos/urls.py
from django.urls import path
from proyectos.views import (
    CrearRol,
    ListarRol,
    ListarUserStory,
    ListarUserStoryFinalizados,
    asignarRol,
    asignarSprint,
    asignarTareasSprint,
    avanzarEstadoTarea,
    cancelarSprint,
    crearTipoUS,
    crearUserStory,
    verUserStory,
    desasignarRol,
    desasignarSprint,
    editarRol,
    eliminarRol,
    eliminarUserStory,
    finalizarProyecto,
    finalizarSprint,
    home,
    iniciarSprint,
    miembroCrear,
    miembroEliminar,
    modificarUserStory,
    modificarUserStoryKanban,
    retrocederEstadoTarea,
    tableroKanban,
    verMiembros,
    verProyecto,
    crearProyecto,
    ListarTipoUserStory,
    iniciarProyecto,
    cancelarProyecto,
    listarProyectos,
    eliminarProyecto,
    modificarProyecto,
    proy,
    crearSprint,
    listarSprints,
    verHistorial,
    modificarSprints,
    eliminarSprint,
    eliminarTipo,
    verRoles,
    modificarTipoUS,
    cancelarUs,
    miembroSprintCrear,
    verMiembrosSprint,
    miembroSprintEliminar,
    burndownchart,
)

urlpatterns = [
    path("", proy, name="proy"),
    path("home/", home, name="home"),
    path("nuevo/", crearProyecto.as_view(), name="nuevo_proyecto"),
    path("listar/", listarProyectos.as_view(), name="listar_proyectos"),
    path("eliminar/<int:id_proyecto>/", eliminarProyecto, name="eliminar_proyectos"),
    path("<int:id_proyecto>/", verProyecto, name="ver_proyecto"),
    path("modificar/<int:id_proyecto>/", modificarProyecto, name="modificar_proyecto"),
    path("<int:id_proyecto>/iniciar/", iniciarProyecto, name="iniciar_proyecto"),
    path("<int:id_proyecto>/finalizar/", finalizarProyecto, name="finalizar_proyecto"),
    path("<int:id_proyecto>/cancelar/", cancelarProyecto, name="cancelar_proyecto"),
    path("<int:id_proyecto>/sprint", crearSprint, name="nuevo_sprint"),
    path(
        "<int:id_proyecto>/sprint/modificar/<int:id_sprint>",
        modificarSprints,
        name="modificar_sprint",
    ),
    path("<int:id_proyecto>/sprint/listar", listarSprints, name="listar_sprints"),
    path(
        "<int:id_proyecto>/sprint/eliminar/<int:id_sprint>/",
        eliminarSprint,
        name="eliminar_sprint",
    ),
    path(
        "<int:id_proyecto>/sprint/iniciar/<int:id_sprint>/",
        iniciarSprint,
        name="iniciar_sprint",
    ),
    path(
        "<int:id_proyecto>/sprint/cancelar/<int:id_sprint>/",
        cancelarSprint,
        name="cancelar_sprint",
    ),
    path(
        "<int:id_proyecto>/sprint/finalizar/<int:id_sprint>/",
        finalizarSprint,
        name="finalizar_sprint",
    ),
    path(
        "<int:idProyecto>/sprint/kanban/<int:idSprint>/",
        tableroKanban,
        name="kanban",
    ),
    path(
        "<int:idProyecto>/sprint/tareas/<int:idSprint>/",
        asignarTareasSprint,
        name="sprint_tareas",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/tarea/<int:idTarea>/asignar_sprint",
        asignarSprint,
        name="asignar_sprint",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/tarea/<int:idTarea>/desasignar_sprint",
        desasignarSprint,
        name="desasignar_sprint",
    ),
    path(
        "<int:idProyecto>/sprint/kanban/<int:idSprint>/tarea-avanzar/<int:idTarea>/",
        avanzarEstadoTarea,
        name="avanzar_tarea",
    ),
    path(
        "<int:idProyecto>/sprint/kanban/<int:idSprint>/tarea-retroceder/<int:idTarea>/",
        retrocederEstadoTarea,
        name="retroceder_tarea",
    ),
    path(
        "<int:idProyecto>/sprint/kanban/tareas/editar/<int:id_tarea>/",
        modificarUserStoryKanban,
        name="modificar_tarea_kanban",
    ),
    # Historial
    path("<int:id_proyecto>/historial/", verHistorial, name="ver_historial"),
    # Miembros
    path("<int:idProyecto>/miembros/listar/", verMiembros, name="listar_miembros"),
    path("<int:idProyecto>/miembros/nuevo/", miembroCrear, name="nuevo_miembro"),
    # Miembros Sprint
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/miembros/listar/",
        verMiembrosSprint,
        name="listar_miembros_sprint",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/miembros/nuevo/",
        miembroSprintCrear,
        name="nuevo_miembro_sprint",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/miembros/eliminar/<int:idMiembro>/",
        miembroSprintEliminar,
        name="eliminar_miembro_sprint",
    ),
    path(
        "<int:idProyecto>/miembros/eliminar/<int:idMiembro>/",
        miembroEliminar,
        name="eliminar_miembro",
    ),
    path(
        "<int:idProyecto>/miembros/<int:idMiembro>/roles/", verRoles, name="ver_roles"
    ),
    path(
        "<int:idProyecto>/miembros/<int:idMiembro>/roles/<int:idRol>/asignar/",
        asignarRol,
        name="asignar_rol",
    ),
    path(
        "<int:idProyecto>/miembros/<int:idMiembro>/roles/<int:idRol>/desasignar/",
        desasignarRol,
        name="desasignar_rol",
    ),
    # Roles
    path("<int:idProyecto>/roles/nuevo/", CrearRol.as_view(), name="crear_rol"),
    path("<int:idProyecto>/roles/listar/", ListarRol.as_view(), name="listar_roles"),
    path(
        "<int:idProyecto>/roles/eliminar/<int:id_rol>/",
        eliminarRol,
        name="eliminar_rol",
    ),
    path("<int:idProyecto>/roles/editar/<int:id_rol>/", editarRol, name="editar_rol"),
    # User Stories
    path("<int:idProyecto>/tareas/nuevo/", crearUserStory, name="crear_tarea"),
    path(
        "<int:idProyecto>/tareas/listar/",
        ListarUserStory.as_view(),
        name="listar_tareas",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/tareas/listar/finalizados/",
        ListarUserStoryFinalizados.as_view(),
        name="listar_tareas_finalizadas",
    ),
    path(
        "<int:idProyecto>/tipos/listar/",
        ListarTipoUserStory.as_view(),
        name="listar_tipos",
    ),
    path(
        "<int:idProyecto>/tipos/eliminar/<int:id_tipo>/",
        eliminarTipo,
        name="eliminar_tipo",
    ),
    path(
        "<int:idProyecto>/tipos/modificar/<int:id_tipo>/",
        modificarTipoUS,
        name="modificar_tipo",
    ),
    path(
        "<int:idProyecto>/tareas/eliminar/<int:id_tarea>/",
        eliminarUserStory,
        name="eliminar_tarea",
    ),
    path(
        "<int:idProyecto>/tareas/editar/<int:id_tarea>/",
        modificarUserStory,
        name="modificar_tarea",
    ),
    path(
        "<int:idProyecto>/tareas/ver/<int:id_tarea>/",
        verUserStory,
        name="ver_tarea",
    ),
    path(
        "<int:idProyecto>/tareas/tipo/",
        crearTipoUS,
        name="tipos_us",
    ),
    path(
        "<int:idProyecto>/tareas/cancelar/",
        cancelarUs,
        name="cancelar_tareas",
    ),
    path(
        "<int:idProyecto>/sprint/<int:idSprint>/burndownchart/",
        burndownchart,
        name="burndownchart",
    ),
]

is2_sgpa/sgpa/apps/usuarios/urls.py
from django.urls import path
from .views import (
    CrearPerfil,
    ListarPerfil,
    administrador,
    concederAcceso,
    editarPerfil_Admin,
    editarPerfil_General,
    eliminarPerfil,
    home,
    listaAcceso,
    proyectosUsuario,
)


urlpatterns = [
    path("", home, name="home"),
    path("nuevo/", CrearPerfil.as_view(), name="solicitar_acceso"),
    path("listar/", ListarPerfil.as_view(), name="listar_perfiles"),
    path("<int:id_usuario>/", proyectosUsuario, name="proyectos_usuario"),
    path("perfil/<int:id_perfil>/", editarPerfil_General, name="editar_perfilGeneral"),
    path("administrador/", administrador, name="administrador"),
    path("acceso/", listaAcceso, name="lista_acceso"),
    path("editar/<int:id_perfil>/", editarPerfil_Admin, name="editar_perfil"),
    path("eliminar/<int:id_perfil>/", eliminarPerfil, name="eliminar_perfil"),
    path("administrador/<int:id_perfil>", concederAcceso, name="conceder_acceso"),
]

is2_sgpa/sgpa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path(
        "login",
        auth_views.LoginView.as_view(template_name="cuenta/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("", include("usuarios.urls")),
    path("usuarios/", include(("usuarios.urls", "usuarios"), namespace="usuarios")),
    path("proyectos/", include(("proyectos.urls", "proyectos"), namespace="proyectos")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

is2_sgpa/sgpa/apps/usuarios/views.py
from django.db.models import Q
from usuarios.models import Perfil
from django.contrib import messages
from django.urls import reverse_lazy
from proyectos.models import Miembro, Proyecto
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import CreateView
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from usuarios.forms import Perfil_Form, Usuario_Form, PerfilEdit_Form
from django.contrib.auth.models import User, Permission
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

#def home
def home(request):
    """
        :param root_path: root path to search isHiddenWithinTree, defaults to "../data_in/"
        :type root_path: str, optional
    """
    if request.user.is_authenticated:
        return render(request, "home.html")
    else:
        return redirect("login")


# --- Creación de Perfil --- #
#crear perfil
class CrearPerfil(LoginRequiredMixin, CreateView):
    """
    Clase para la creacion de un perfil de usuario
    Hereda de la clase genérica CreateView
    Requiere inicio de sesión
    """

    model = Perfil
    form_class = Perfil_Form
    template_name = "usuarios/nuevo_perfil.html"
    success_url = reverse_lazy("proyectos:home")

    def form_valid(self, form):
        user = User.objects.get(username=self.request.user)
        Perfil.objects.create(
            user=user,
            ci=self.request.POST["ci"],
            telefono=self.request.POST["telefono"],
        )
        return redirect(self.success_url)


# --- Edición de Perfil --- #
#editar perfil general
@login_required
def editarPerfil_General(request, id_perfil):
    """
    Vista para la edición de los datos de un usuario (el email y el ci no puede ser modificado)
    Recibe el request HTTP y el id del perfil de un usuario
    Devuelve la renderización de la información del usuario
    Requiere inicio de sesión
    """
    perfil = Perfil.objects.get(id=id_perfil)
    usuario = User.objects.get(id=perfil.user.id)
    if request.method == "GET":
        perfil_Form = PerfilEdit_Form(instance=perfil)
        usuario_Form = Usuario_Form(instance=usuario)
    else:
        perfil_Form = PerfilEdit_Form(request.POST, instance=perfil)
        usuario_Form = Usuario_Form(request.POST, instance=usuario)
        if all([perfil_Form.is_valid(), usuario_Form.is_valid()]):
            perfil_Form.save(usuario=usuario, telefono=perfil.telefono)
            usuario_Form.save()
        return redirect("usuarios:proyectos_usuario", id_perfil)
    return render(
        request,
        "usuarios/editar_perfilGeneral.html",
        {"perfil_Form": perfil_Form, "usuario_Form": usuario_Form},
    )


# --- Proyectos de Usuario --- #
#proyecto de usuarios
@login_required
def proyectosUsuario(request, id_usuario):
    """
    Función que permite visualizar los proyectos de un determinado usuario
    Recibe el request HTTP y el id del usuario
    Retorna la renderización de los proyectos asociados en el template detallado
    Requiere inicio de sesión
    """

    usuario = User.objects.get(id=id_usuario)
    perfil = Perfil.objects.get(user=usuario)
    miembro = Miembro.objects.filter(idPerfil=perfil.id)
    return render(request, "usuarios/proyectos.html", {"miembros": miembro})


# ******************************** #
# *    Apartado Administrador    * #
# ******************************** #


@login_required
@permission_required("usuarios.autorizar_usuario", login_url="usuarios:home")
def administrador(request):
    """
    Obtiene la información acerca de todos los proyectos existentes, las solicitudes de acceso al sistema y el control de usuarios
    Recibe el request HTTP
    Retorna la renderización de la información ya mencionada en el template especificado
    Requiere inicio de sesión y permisos administrador
    """

    proyectos = Proyecto.objects.all()
    permiso = Permission.objects.get(codename="acceso_usuario")
    usuario = User.objects.filter(~Q(user_permissions=permiso), ~Q(id=1))
    perfilesAcceso = Perfil.objects.none()
    if len(usuario) > 0:
        perfilesAcceso = Perfil.objects.filter(Q(user=usuario[0]))
        for x in range(1, len(usuario)):
            perfilesAcceso |= Perfil.objects.filter(Q(user=usuario[x]))
    return render(
        request,
        "usuarios/administrador.html",
        {"perfilesAcceso": perfilesAcceso, "proyectos": proyectos},
    )


# --- Listar Solicitudes de Acceso --- #
#lista de accesos
@login_required
@permission_required("usuarios.autorizar_usuario", login_url="usuarios:home")
def listaAcceso(request):
    """
    Lista de las solicitudes de acceso al sistema
    Retorna la rendererización de la información solicitada en el template
    Recibe el request HTTP
    Requiere inicio de sesión y permisos administrador
    """

    perm = Permission.objects.get(codename="acceso_usuario")
    usuario = User.objects.filter(~Q(user_permissions=perm))
    perfiles = Perfil.objects.filter(Q(user=usuario[0]))
    for x in range(1, len(usuario)):
        perfiles |= Perfil.objects.filter(Q(user=usuario[x]))
    contexto = {"perfiles": perfiles}
    return render(request, "usuarios/usuario_acceso.html", contexto)


# --- Conceder Acceso al Sistema --- #
#conceder Acceso
@login_required
@permission_required("usuarios.autorizar_usuario", login_url="usuarios:home")
def concederAcceso(request, id_perfil):
    """
    Concede permiso de acceso al sistema y envía un email notificando lo acontecido al usuario
    Recibe el request HTTP y el id del perfil de usuario
    El retorno es una redirección a la página de solicitud
    Requiere inicio de sesión y permisos administrador
    """

    perfil = Perfil.objects.get(id=id_perfil)
    usuario = User.objects.get(id=perfil.user.id)
    perm = Permission.objects.get(codename="acceso_usuario")
    usuario.user_permissions.add(perm)
    send_mail(
        "Solicitud de acceso a SGPA",
        "¡Bienvenido a SGPA! Su solicitud de acceso al sistema fue aceptada",
        settings.EMAIL_HOST_USER,
        [usuario.email],
    )
    return redirect("usuarios:administrador")


# --- Listar Perfiles --- #
#listar perfiles
class ListarPerfil(LoginRequiredMixin, ListView):
    """
    Clase utilizada para listar los perfiles de usuarios existentes
    Hereda de la clase ListView
    Requiere inicio de sesión y permiso de administrador
    """

    redirect_field_name = "redirect_to"
    model = Perfil
    template_name = "usuarios/listar_perfiles.html"


# --- Editar Perfil --- #
#editar perfil admin
@login_required
def editarPerfil_Admin(request, id_perfil):
    """
    Vista para la edición de los datos de un usuario (el email puede ser modificado)
    Recibe el request HTTP y el id del perfil de un usuario
    Devuelve la renderización de la información del usuario
    Requiere inicio de sesión y permiso de administrador
    """

    perfil = Perfil.objects.get(id=id_perfil)
    usuario = User.objects.get(id=perfil.user.id)
    if request.method == "GET":
        perfil_Form = Perfil_Form(instance=perfil)
        usuario_Form = Usuario_Form(instance=usuario)
    else:
        perfil_Form = Perfil_Form(request.POST, instance=perfil)
        usuario_Form = Usuario_Form(request.POST, instance=usuario)
        if all([perfil_Form.is_valid(), usuario_Form.is_valid()]):
            perfil_Form.save(ci=perfil.ci, usuario=usuario, telefono=perfil.telefono)
            usuario_Form.save()
        return redirect("usuarios:listar_perfiles")
    return render(
        request,
        "usuarios/editar_perfil.html",
        {"perfil_Form": perfil_Form, "usuario_Form": usuario_Form},
    )


# --- Eliminar Perfil --- #
#eliminar perfil
@login_required
def eliminarPerfil(request, id_perfil):
    """
    Elimina el perfil del usuario solicitado
    Recibe el request HTTP y el id del perfil de usuario
    Retorna la renderización en el template especificado, en el cual solicita confirmación y luego redirige a la lista de perfiles
    Requiere inicio de sesión y permiso de administrador
    """

    perfil = Perfil.objects.get(id=id_perfil)
    miembro = Miembro.objects.filter(idPerfil=perfil.id)
    if not miembro:
        if request.method == "POST":
            usuario = User.objects.get(id=perfil.user.id)
            usuario.delete()
            perfil.delete()
            return redirect("usuarios:listar_perfiles")
        return render(request, "usuarios/eliminar_perfil.html", {"perfil": perfil})
    else:
        messages.add_message(
            request,
            messages.ERROR,
            "No se puede eliminar al usuario: %s  porque forma parte de un proyecto"
            % perfil.user.first_name,
        )
        return redirect("usuarios:listar_perfiles")

is2_sgpa/sgpa/templates/sprints/agregar_tareas.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if messages %}
{% for message in messages %}
{% if 'error' in message.tags %}
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endif %}
{% if 'info' in message.tags %}
<div class="alert alert-dismissible alert-info" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endif %}
{% endfor %}
{% endif %}
<ins>
    <h3 align="center">Asignacion de tareas al Sprint - {{proyecto.nombre}}</h3>
</ins>
<p align="center">
    <a class="btn btn-primary" href="{% url 'proyectos:listar_sprints' idProyecto %}" role="button">Volver</a>
</p>
<div style="display: flex; justify-content: space-between;">
    {% for dato in datos %}
    <div style="display: flex; flex-direction: column;">
        <h3>{{ dato.columna }}</h3>
        <div class="kanban-tablero">
            {% for tarea in dato.tareas %}
            <div class="kanban-container">
                <div class="kanban-card">
                    <div class="kanban-card-body">
                        <div style="width: 100%; justify-content: space-between; display: flex;">
                            <span class="kanban-tag kanban-tag-teal mb-3">Prioridad: {{tarea.prioridad_total}}</span>
                            {% if tarea.sprint %}
                            {% if tarea.estado.id != cancelado.id %}
                            <a href="{% url 'proyectos:modificar_tarea_kanban' idProyecto tarea.id %}"
                                class="btn boton-color"><i class="fas fa-pen"></i></a>
                            {% endif %}
                            {% endif %}
                        </div>
                        <h4>{{ tarea.nombre }}</h4>
                        <p>{{ tarea.descripcion }}</p>
                        {% if tarea.estado.id == cancelado.id %}
                        <p style="margin: 0 0 0px; color: #dc3545;">Estado: {{tarea.estado}}</p>
                        {% endif %}
                        <p>Horas estimadas: {{ tarea.horas_estimadas }}</p>
                        <div class=" kanban-user" style="width:100%; justify-content: space-between;">
                            <div class="kanban-user-info">
                                <h5>{{ tarea.desarrollador }}</h5>
                                {% for rol in tarea.desarrollador.roles.all %}
                                {% if forloop.last %}
                                <small>{{ rol.nombre }}</small>
                                {% else %}
                                <small>{{ rol.nombre }},</small>
                                {% endif %}
                                {% endfor %}
                            </div>
                            {% if tarea.estado.id != cancelado.id %}
                            {% if tarea.sprint == None %}
                            <a class="btn boton-color mb-2" style="width: 80px; height: 40px;"
                                href="{% url 'proyectos:asignar_sprint' idProyecto idSprint tarea.id %}">Asignar</a>
                            {% else %}
                            <a class="btn btn-danger mb-2 style=" width: 80px; height: 40px;"
                                href="{% url 'proyectos:desasignar_sprint' idProyecto idSprint tarea.id %}">Retirar</a>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

is2_sgpa/sgpa/templates/sprints/burndownchart.html
{% extends 'base.html'%}

{%block content%}
<div>
    <canvas id="myChart" width="70" height="30"></canvas>
</div>
<div>
    <a href="{% url 'proyectos:kanban' idProyecto idSprint %}" class="btn btn-primary">Volver</a>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    const ctx = document.getElementById('myChart');
    var ideal_data = {{ datf1| safe}}
    var ideal_labels = {{ df1| safe}}
    var duracion = {{ duracion| safe}}
    var paso = {{ paso| safe}}
    var capacidad = {{ capacidad| safe}}
    var dias = {{ dias| safe}}
    var horas_trabajadas = {{ horas_trabajadas| safe}}
    new Chart(ctx, {
        type: 'line',
        data: {
            labels: dias,
            datasets: [{
                label: 'Ideal',
                data: ideal_data,
                fill: false,
                borderColor: 'rgb(255, 0, 0)',
                borderWidth: 3,
                tension: 0.1
            },
            {
                label: 'Actual',
                data: horas_trabajadas,
                fill: false,
                borderColor: 'rgb(0, 192, 0)',
                borderWidth: 3,
                tension: 0.1
            }
            ]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true,
                    max: capacidad,
                    min: 0,
                    ticks: {
                        stepSize: 5
                    }
                },
            }
        }
    });
</script>
{%endblock content%}

is2_sgpa/sgpa/templates/sprints/listar_sprints.html
{% extends 'base.html' %}
{% block content%}
<br>
{% if messages %}
{% for message in messages %}
{% if 'error' in message.tags %}
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endif %}
{% if 'info' in message.tags %}
<div class="alert alert-dismissible alert-info" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endif %}
{% endfor %}
{% endif %}
<div class="container-fluid">
    <ins>
        <h3 align="center">Sprints - {{proyecto.nombre}}</h3>
    </ins>
    <br>
    <div class="row">
        <div class="col-md-1">

        </div>
        <div class="col-md-10">
            <table class="table">
                <thead>
                    <tr class="table-primary">
                        <th>Posición</th>
                        <th>Objetivo</th>
                        <th>Estado</th>
                        <th>Num. Tareas</th>
                        <th>Duración</th>
                        <th>Tiempo Disponible</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sprint in sprints %}
                    {% if sprint.warning_cap %}
                    <tr style="background-color: #f9d6ac;">
                        {% else %}
                    <tr>
                        {% endif %}
                        <td scope="col">{{sprint.posicion}}</td>
                        <td scope="col"><a href="{% url 'proyectos:kanban' idProyecto sprint.id %}">
                                {{sprint.objetivos}} </a></td>
                        <td scope="col">{{sprint.estado}}</td>
                        <td scope="col">{{sprint.numTareas}}</td>
                        <td scope="col">{{sprint.duracion}}</td>
                        {% if sprint.warning_cap %}
                        <td scope="col">{{sprint.tiempo_disponible}} <i style="color: #ff5400;"
                                class="fa-solid fa-triangle-exclamation"></i>
                        </td>
                        {% else %}
                        <td scope="col">{{sprint.tiempo_disponible}}</td>
                        {% endif %}
                        <td scope="col">
                            {% if user.id == proyecto.scrumMaster.user.id or perms.proyectos.modificar_sprint %}
                            <a href="{% url 'proyectos:modificar_sprint' idProyecto sprint.id %}"
                                class="btn boton-color"><i class="fas fa-pen"></i></a>
                            {% endif %}
                            {% if user.id == proyecto.scrumMaster.user.id or perms.proyectos.eliminar_sprint %}
                            <a href="{% url 'proyectos:eliminar_sprint' idProyecto sprint.id %}"
                                class="btn btn-danger"><i class="fas fa-trash"></i></a>
                            {% endif %}
                            {% if user.id == proyecto.scrumMaster.user.id or perms.proyectos.iniciar_sprint %}
                            <a href="{% url 'proyectos:iniciar_sprint' idProyecto sprint.id %}"
                                class="btn boton-iniciar"><i class="fa-solid fa-play"></i></a>
                            {% endif %}
                            {% if user.id == proyecto.scrumMaster.user.id or perms.proyectos.finalizar_sprint %}
                            <a href="{% url 'proyectos:finalizar_sprint' idProyecto sprint.id %}"
                                class="btn boton-finalizar"><i class="fa-solid fa-check"></i></a>
                            {% endif %}
                            {% if user.id == proyecto.scrumMaster.user.id or perms.proyectos.cancelar_sprint %}
                            <a href="{% url 'proyectos:cancelar_sprint' idProyecto sprint.id %}"
                                class="btn boton-cancelar"><i class="fa-solid fa-xmark"></i></a>
                            {% endif %}
                            {% if user.id == proyecto.scrumMaster.user.id or perms.proyectos.agregar_tareas_sprint %}
                            <a href="{% url 'proyectos:sprint_tareas' idProyecto sprint.id %}"
                                class="btn boton-agregar">Agregar Tareas</a>
                            {% endif %}
                            <a href="{% url 'proyectos:listar_miembros_sprint' idProyecto sprint.id %}"
                                class="btn boton-agregar">Miembros</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p align="center">
                {% if user.id == proyecto.scrumMaster.user.id or perms.proyectos.crear_sprint %}
                <a href="{% url 'proyectos:nuevo_sprint' idProyecto %}" class="btn btn-primary" role="button">Crear
                    Sprint</a>
                {% endif %}
                <a class="btn btn-primary" href="{% url 'proyectos:ver_proyecto' idProyecto %}" role="button">Volver</a>
            </p>
        </div>
        <div class="col-md-1">

        </div>
    </div>
</div>
{% endblock %}